<script lang="ts">
	import { onMount } from 'svelte';
	import AOS from 'aos';
	import Header from '../components/ui/Header.svelte';
	import '../app.pcss';
	import 'aos/dist/aos.css';
	const inter = {
		subsets: ['latin'],
		variable: '--font-inter',
		display: 'swap'
	};

	export const metadata = {
		title: 'Create Next App',
		description: 'Generated by create next app',
	}
	onMount(() => {
    if (typeof window !== 'undefined') {
      AOS.init();
    }
  });
</script>


<svelte:body class={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}/>
<div class="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
	<Header />
		<slot />
	<!-- <Banner /> -->
</div>